services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    networks:
      - homenet
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - xxxx:xx
    volumes:
      - /media/external_drive:/srv # files will be stored here
      - ./database:/database # users info/settings will be stored here
      - ./config:/config # config file
    restart: unless-stopped

networks:
  homenet:
    external: true
