services:
  app:
    image: 'jc21/nginx-proxy-manager:2.15.1'
    restart: unless-stopped

    networks:
      - homenet

    ports:
      # These ports are in format <host-port>:<container-port>
      - 'xxxx:xx' # Public HTTP Port
      - 'xxxx:xx' # Public HTTPS Port
      - 'xxxx:xx' # Admin Web Port
      # Add any other Stream port you want to expose
      # - 'xxxx:xx' # FTP

    environment:
      TZ: "Europe/London"
      IP_RANGES_FETCH_ENABLED: 'false'
      DISABLE_IPV6: 'true'

      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  homenet:
    external: true
